feat: encoders accept strings
smithy-lang/smithy-typescript pull request #1176
Opened 2024-02-29 18:10 UTC by kuhe

Clients currently have two internal fields of type `Encoder`, currently `Uint8Array => string`.

These have been updated to be `Uint8Array | string => string`, to allow direct conversion of utf8 strings to base64, rather than requiring a `Uint8Array` input.

The `Encoder` type has not been changed, since it is public.

2024-02-29 19:26 UTC, kuhe commented
This will allow users to send strings as input for fields that otherwise require `Uint8Array`, which can be cumbersome to initialize.

Though it is as easy as writing `Buffer.from('abcd')`, discovering this is somewhat obscure because it's not obvious that Buffer is a Uint8Array.

2024-03-05 17:04 UTC, kuhe commented
I verified this using SES

```ts
import * as sesClientModule from "@aws-sdk/client-ses";
import nodemailer from "nodemailer";

export const sendEmailWithAttachments = (from = "@email", to = "@email") => {
  const ses = new sesClientModule.SESClient({
    region: "us-west-2",
  });

  ses.middlewareStack.add(
    (next, context) => async (args: any) => {
      console.log("AWS SDK context", context.clientName, context.commandName);

      args.input.RawMessage.Data = args.input.RawMessage.Data.toString();
      console.log("AWS SDK request input", args.input);

      console.log("AWS SDK raw request", args.request);
      const result = await next(args);
    //   console.log("AWS SDK raw response", result.response);
      console.log("AWS SDK response metadata:", result.output.$metadata);
      // console.log("AWS SDK request output:", result.output);
      return result;
    },
    {
      name: "MyMiddleware",
      step: "build",
      override: true,
    }
  );

  const transporter = nodemailer.createTransport({
    SES: { ses, aws: sesClientModule },
  });

  return new Promise((resolve, reject) => {
    transporter.sendMail(
      {
        from,
        to,
        subject: "using string input for RawMessage",
        text: "using string input for RawMessage",
        attachments: [{ content: "Hello World!", filename: "hello.txt" }],
      },
      (err, info) => {
        if (err) {
          reject(err);
        } else {
          resolve(info);
        }
      }
    );
  });
};

sendEmailWithAttachments();

```

2024-03-05 20:01 UTC, syall requested changes
For inputs that take `Uint8Array | string`, can we do a runtime check if it's not one of these types to restrict the types more?

I see `typeof xxx === "string"` is used, but can we use `instanceof Uint8Array` checks?

2024-03-05 20:39 UTC, syall approved these changes

2024-03-07 15:57 UTC, merged