fix(middleware-apply-body-checksum): fix request copying with clone
smithy-lang/smithy-typescript pull request #1324
Opened 2024-07-02 11:56 UTC by syall

*Issue #, if available:*

N/A

*Description of changes:*

Fixed a subtle bug when request copying, otherwise methods like `clone()` may not be copied over.

If one or more of the packages in the `/packages` directory has been modified, be sure `yarn changeset add` has been run and its output has
been committed and included in this pull request. See CONTRIBUTING.md.

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-10 17:33 UTC, kuhe commented on packages/middleware-apply-body-checksum/src/applyMd5BodyChecksumMiddleware.ts
> +        const cloned = request.clone();
This isn't a safe assumption. 

`HttpRequest.isInstance(request)` is incorrectly implemented. It only checks that a request is duck-like an HttpRequest **interface**. The `clone` method only exists on the `HttpRequest` **class**.

It wasn't a good idea naming interfaces and classes the same, even worse that they aren't identical types.

2024-07-10 17:33 UTC, kuhe requested changes
Note to self: implement static `HttpRequest.clone()` that accepts `HttpRequest` interface. Deprecate instance method.

2024-07-15 18:22 UTC, kuhe approved these changes

2024-07-18 16:58 UTC, kuhe commented
This is no longer necessary due to https://github.com/smithy-lang/smithy-typescript/pull/1345

2024-07-18 17:00 UTC, kuhe commented
re-opening because this PR is still good for code clarity

2024-07-18 17:09 UTC, hpmellema approved these changes

2024-07-18 17:16 UTC, merged